### ISSUE TITLE
error with issue dates 

### ISSUE THREAD

**Issue by sms-34** [sfu-dhil/new-narratives#63]
### What isn’t working as expected on the website?

There are multiple different issue dates for the same entry. 

**Example**

[Original stories from real life; with conversations, calculated to regulate the affections, and form the mind to truth and goodness.] (https://dhil.lib.sfu.ca/newn/work/772)
Author: Wollstonecraft, Mary
Date Issued: **1791**
[Original stories from real life; with conversations, calculated to regulate the affections, and form the mind to truth and goodness.] (https://dhil.lib.sfu.ca/newn/work/773)
Author: Wollstonecraft, Mary
Date Issued: **1799**
[Original stories from real life; with conversations, calculated to regulate the affections, and form the mind to truth and goodness.](https://dhil.lib.sfu.ca/newn/work/774)
Author: Wollstonecraft, Mary
Date Issued: **1807**

### If you encountered an error message, please copy the relevant details or take a screenshot and paste it below.

NA

### What is the URL of the page where you encountered the bug?

https://dhil.lib.sfu.ca/newn/date_category/1

### What steps did you take before you encountered the bug?

1. go to page https://dhil.lib.sfu.ca/newn/date_category/1
2. check different issue dates 

### What browser, operating system, and device were you using when you encountered the error?

Ede, windows 10

**Comment by ubermichael** [comment]
If there is a bug here it is in data entry.

But I don't think this is wrong. That work was published multiple times, which is why it has multiple entries with different dates.
