### ISSUE TITLE
Non-English author names

### ISSUE THREAD

**Issue by sms-34** [sfu-dhil/new-narratives#65]
### Describe the feature

There are many authors with non-English names in the database. Searching for those names is challenging as you have to type the name exactly as written in the database, which might not be available for all keyboards.  

For example: one Arabic name is Rābiʻah (https://dhil.lib.sfu.ca/newn/person/search?q=Ra%CC%84bi%CA%BBah)

If I type this name differently: Rabiah (https://dhil.lib.sfu.ca/newn/person/search?q=rabiah+) or Rabi'ah (https://dhil.lib.sfu.ca/newn/person/search?q=rabi%27ah+)--there will be no search results. 

### How will this feature enhance your project and further the project’s overall goals? Who will benefit from this feature (i.e. all users; the project team)?

All users 

### Are there any alternatives for this feature? Are there any consequences for your project if this feature is not implemented?

No alternatives

### Please share any examples of this feature, or one similar to it, that you have encountered in other contexts.

This feature will simplify the search process for all users.

**Comment by ubermichael** [comment]
This is a fundamental limitation of the database. The search will work with `"Rabiʻah"` at least, but this isn't much of an improvement.
